/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── SSENSE-inspired stark monochrome palette ─────────────
        // Token names kept from the previous theme so components
        // don't need touching: "cream" = paper, "green-*" = ink.
        "cream":                    "#FFFFFF",
        "cream-dark":               "#F5F5F5",
        "cream-darker":             "#EBEBEB",
        "green-deep":               "#0A0A0A",
        "green-mid":                "#1F1F1F",
        "green-muted":              "#737373",
        "green-ghost":              "#C9C9C9",
        "warm-border":              "#E2E2E2",
        "acid":                     "#DFFF00",
        // ── Semantic colour overrides ─────────────────────────────
        "primary":                  "#0A0A0A",
        "on-primary":               "#FFFFFF",
        "primary-container":        "#1F1F1F",
        "on-primary-container":     "#EBEBEB",
        "primary-fixed":            "#EBEBEB",
        "primary-fixed-dim":        "#C9C9C9",
        "on-primary-fixed":         "#0A0A0A",
        "on-primary-fixed-variant": "#1F1F1F",
        "secondary":                "#1F1F1F",
        "on-secondary":             "#FFFFFF",
        "secondary-container":      "#EBEBEB",
        "on-secondary-container":   "#0A0A0A",
        "secondary-fixed":          "#EBEBEB",
        "secondary-fixed-dim":      "#C9C9C9",
        "on-secondary-fixed":       "#0A0A0A",
        "on-secondary-fixed-variant":"#1F1F1F",
        "tertiary":                 "#404040",
        "tertiary-container":       "#737373",
        "on-tertiary":              "#FFFFFF",
        "on-tertiary-container":    "#F5F5F5",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
        "surface":                  "#FFFFFF",
        "surface-dim":              "#F0F0F0",
        "surface-bright":           "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low":    "#F7F7F7",
        "surface-container":        "#F5F5F5",
        "surface-container-high":   "#EFEFEF",
        "surface-container-highest":"#EBEBEB",
        "surface-variant":          "#EFEFEF",
        "surface-tint":             "#1F1F1F",
        "on-surface":               "#0A0A0A",
        "on-surface-variant":       "#737373",
        "outline":                  "#737373",
        "outline-variant":          "#E2E2E2",
        "inverse-surface":          "#0A0A0A",
        "inverse-on-surface":       "#FFFFFF",
        "inverse-primary":          "#C9C9C9",
        "background":               "#FFFFFF",
        "on-background":            "#0A0A0A",
      },
      fontFamily: {
        // SSENSE-style Helvetica stack — system fonts, no webfont cost
        "display":  ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        "mono":     ["Space Mono", "Courier New", "monospace"],
        "headline": ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        "body":     ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        "label":    ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        sans:       ["Helvetica Neue", "Helvetica", "Arial", "system-ui", "sans-serif"],
      },
      borderRadius: {
        // Sharp everything — no rounded corners in this design language
        DEFAULT: "0",
        sm:      "0",
        lg:      "0",
        xl:      "0",
        "2xl":   "0",
        full:    "0",
      },
      animation: {
        "fade-up":    "fadeUp 0.7s ease both",
        "fade-up-d1": "fadeUp 0.7s 0.15s ease both",
        "fade-up-d2": "fadeUp 0.7s 0.30s ease both",
        "fade-up-d3": "fadeUp 0.7s 0.50s ease both",
        "float":      "float 6s ease-in-out infinite",
        "float-d1":   "float 7s 1s ease-in-out infinite",
        "float-d2":   "float 8s 2s ease-in-out infinite",
        "float-d3":   "float 6.5s 0.5s ease-in-out infinite",
        "float-d4":   "float 7.5s 1.5s ease-in-out infinite",
        "shimmer":    "shimmer 1.4s ease infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(22px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-14px)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
      },
    },
  },
  plugins: [],
};
