/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Cream + Deep Green editorial palette ──────────────────
        "cream":                    "#F0EBE0",
        "cream-dark":               "#E5DDD1",
        "cream-darker":             "#D8CFC4",
        "green-deep":               "#1A2E1E",
        "green-mid":                "#2C4A35",
        "green-muted":              "#4F6655",
        "green-ghost":              "#A8BCA8",
        "warm-border":              "#C0B8AF",
        // ── Semantic colour overrides ─────────────────────────────
        "primary":                  "#1A2E1E",
        "on-primary":               "#F0EBE0",
        "primary-container":        "#2C4A35",
        "on-primary-container":     "#C8DCC8",
        "primary-fixed":            "#C8DCC8",
        "primary-fixed-dim":        "#A0BCA0",
        "on-primary-fixed":         "#0A1A0C",
        "on-primary-fixed-variant": "#1A2E1E",
        "secondary":                "#2C4A35",
        "on-secondary":             "#F0EBE0",
        "secondary-container":      "#D4E4D4",
        "on-secondary-container":   "#0C1F10",
        "secondary-fixed":          "#D4E4D4",
        "secondary-fixed-dim":      "#B0CCB0",
        "on-secondary-fixed":       "#0C1F10",
        "on-secondary-fixed-variant":"#2C4A35",
        "tertiary":                 "#5C3A1E",
        "tertiary-container":       "#8B6040",
        "on-tertiary":              "#F0EBE0",
        "on-tertiary-container":    "#F0DCC8",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
        "surface":                  "#F0EBE0",
        "surface-dim":              "#E0D9CE",
        "surface-bright":           "#F8F4ED",
        "surface-container-lowest": "#FAF7F2",
        "surface-container-low":    "#EAE4D9",
        "surface-container":        "#E5DDD1",
        "surface-container-high":   "#DDD5C8",
        "surface-container-highest":"#D5CDBE",
        "surface-variant":          "#DDD5C8",
        "surface-tint":             "#2C4A35",
        "on-surface":               "#1A2E1E",
        "on-surface-variant":       "#4F6655",
        "outline":                  "#4F6655",
        "outline-variant":          "#C0B8AF",
        "inverse-surface":          "#1A2E1E",
        "inverse-on-surface":       "#F0EBE0",
        "inverse-primary":          "#A8BCA8",
        "background":               "#F0EBE0",
        "on-background":            "#1A2E1E",
      },
      fontFamily: {
        "display":  ["Bebas Neue", "Impact", "sans-serif"],
        "mono":     ["Space Mono", "Courier New", "monospace"],
        "headline": ["Epilogue", "serif"],
        "body":     ["Manrope", "sans-serif"],
        "label":    ["Manrope", "sans-serif"],
        sans:       ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "9999px",
      },
      animation: {
        "fade-up":    "fadeUp 0.7s ease both",
        "fade-up-d1": "fadeUp 0.7s 0.15s ease both",
        "fade-up-d2": "fadeUp 0.7s 0.30s ease both",
        "fade-up-d3": "fadeUp 0.7s 0.50s ease both",
        "float":      "float 6s ease-in-out infinite",
        "float-d1":   "float 7s 1s ease-in-out infinite",
        "float-d2":   "float 8s 2s ease-in-out infinite",
        "float-d3":   "float 6.5s 0.5s ease-in-out infinite",
        "float-d4":   "float 7.5s 1.5s ease-in-out infinite",
        "shimmer":    "shimmer 1.4s ease infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(22px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-14px)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
      },
    },
  },
  plugins: [],
};
