/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1b1b",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        "outline": "#707975",
        "surface-tint": "#29695b",
        "on-error": "#ffffff",
        "on-secondary-container": "#536662",
        "surface-variant": "#e5e2e1",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#00201a",
        "secondary-fixed-dim": "#b6cbc6",
        "secondary-fixed": "#d2e7e2",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#3f4945",
        "error": "#ba1a1a",
        "surface-bright": "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-highest": "#e5e2e1",
        "primary": "#00342b",
        "primary-fixed-dim": "#94d3c1",
        "primary-container": "#004d40",
        "primary-fixed": "#afefdd",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#313030",
        "surface": "#fcf9f8",
        "on-secondary-fixed": "#0c1f1c",
        "on-primary-container": "#7ebdac",
        "background": "#fcf9f8",
        "tertiary-container": "#8b0700",
        "on-background": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bfc9c4",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#065043",
        "surface-container-low": "#f6f3f2",
        "secondary-container": "#cfe4df",
        "on-secondary-fixed-variant": "#384a47",
        "tertiary": "#610300",
        "on-tertiary-container": "#ff9280",
        "inverse-primary": "#94d3c1",
        "secondary": "#4f625e",
      },
      fontFamily: {
        "headline": ["Epilogue", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        "fade-up":    "fadeUp 0.7s ease both",
        "fade-up-d1": "fadeUp 0.7s 0.15s ease both",
        "fade-up-d2": "fadeUp 0.7s 0.30s ease both",
        "fade-up-d3": "fadeUp 0.7s 0.50s ease both",
        "float":      "float 6s ease-in-out infinite",
        "float-d1":   "float 7s 1s ease-in-out infinite",
        "float-d2":   "float 8s 2s ease-in-out infinite",
        "float-d3":   "float 6.5s 0.5s ease-in-out infinite",
        "float-d4":   "float 7.5s 1.5s ease-in-out infinite",
        "shimmer":    "shimmer 1.4s ease infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(22px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-14px)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
      },
    },
  },
  plugins: [],
};
