import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — Mira",
  description: "How Mira collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-surface">
      {/* Header */}
      <div className="border-b border-primary/5 bg-surface-container-low px-6 py-5">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-xl font-bold tracking-tighter text-primary font-headline">
            Mira
          </Link>
          <span className="text-xs font-bold tracking-widest uppercase text-outline font-label">
            Privacy Policy
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16 pb-32">
        <h1 className="font-headline text-4xl font-extrabold text-primary mb-2">Privacy Policy</h1>
        <p className="text-on-surface-variant font-body text-sm mb-12">Updated March 21, 2026</p>

        <div className="space-y-10 font-body text-on-surface-variant text-sm leading-relaxed">

          <p>
            Mira ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy
            explains how your personal information is collected, used, and disclosed by Mira.
            This Privacy Policy applies to our website and application. By accessing or using our
            Service, you agree to our collection, storage, use, and disclosure of your personal
            information as described here.
          </p>

          <Section title="Definitions and Key Terms">
            <ul className="space-y-3 list-disc list-inside">
              <li><strong>Cookie:</strong> A small amount of data generated by a website and saved by your browser — used to identify your browser, provide analytics, or remember preferences.</li>
              <li><strong>Company:</strong> When this policy mentions "we," "us," or "our," it refers to Mira.</li>
              <li><strong>Country:</strong> United States, where Mira is based.</li>
              <li><strong>Device:</strong> Any internet-connected device used to visit Mira and use its services.</li>
              <li><strong>IP Address:</strong> A number assigned to every device connected to the Internet, often used to identify approximate location.</li>
              <li><strong>Personal Data:</strong> Any information that directly or indirectly allows for the identification of a natural person.</li>
              <li><strong>Service:</strong> The Mira platform and application.</li>
              <li><strong>Website:</strong> Mira's site, accessible at https://mira-4.vercel.app</li>
              <li><strong>You:</strong> A person registered with Mira to use the Services.</li>
            </ul>
          </Section>

          <Section title="What Information Do We Collect?">
            <p>We collect information when you visit our website, register an account, or fill out a form:</p>
            <ul className="mt-3 space-y-1 list-disc list-inside">
              <li>Email address</li>
              <li>Password (hashed — we never store plaintext passwords)</li>
              <li>Fashion images you choose to upload</li>
              <li>Search queries (text and image)</li>
            </ul>
          </Section>

          <Section title="How Do We Use The Information We Collect?">
            <ul className="space-y-1 list-disc list-inside">
              <li>To personalize your experience and surface relevant styles</li>
              <li>To associate your uploads and saves with your account</li>
              <li>To improve our AI search and recommendation quality</li>
              <li>To respond to customer service requests</li>
              <li>To send account-related emails (no marketing without consent)</li>
            </ul>
          </Section>

          <Section title="Do We Share Your Information?">
            <p>
              We do not sell your personal information. We may share information with trusted
              third-party service providers who help us operate the platform — including cloud
              hosting (Railway), image storage (Cloudinary), authentication (Supabase), and
              frontend delivery (Vercel). These providers are contractually bound to protect
              your data and use it only to perform services on our behalf.
            </p>
            <p className="mt-3">
              We may disclose information to government or law enforcement officials if required
              by law or to protect the rights and safety of our users.
            </p>
          </Section>

          <Section title="How We Protect Your Information">
            <p>
              All data is transmitted over HTTPS (SSL/TLS). Passwords are never stored in
              plaintext — authentication is handled by Supabase, which uses bcrypt hashing.
              Session tokens (JWTs) are stored in your browser's localStorage and expire
              automatically. We implement rate limiting on all API endpoints to prevent abuse.
            </p>
          </Section>

          <Section title="Cookies and Local Storage">
            <p>
              Mira uses browser localStorage (not traditional cookies) to store your session
              token so you remain logged in between visits. No personally identifiable
              information is stored in cookies. You can clear localStorage at any time through
              your browser settings, which will sign you out.
            </p>
          </Section>

          <Section title="How Long Do We Keep Your Information?">
            <p>
              We retain your account information for as long as your account is active. If you
              delete your account, we will remove your personal data from active systems within
              60 days. Uploaded images stored in Cloudinary are deleted upon account deletion
              upon request.
            </p>
          </Section>

          <Section title="Can I Update or Delete My Information?">
            <p>
              Yes. You can request that we update, correct, or delete your personal information
              by contacting us. You can also delete your account at any time from your profile
              settings, which will remove your data from our active systems.
            </p>
          </Section>

          <Section title="Kids' Privacy">
            <p>
              Mira is not directed to anyone under the age of 13. We do not knowingly collect
              personal information from children under 13. If you believe your child has
              provided us with personal data, please contact us and we will delete it promptly.
            </p>
          </Section>

          <Section title="GDPR (European Users)">
            <p>
              If you are located in the European Economic Area, you have the right to access,
              update, retrieve, and request deletion of your personal data. All personal data
              is processed in accordance with GDPR principles — collected for specific purposes,
              stored only as long as necessary, and protected with appropriate technical
              safeguards. Contact us to exercise any of these rights.
            </p>
          </Section>

          <Section title="California Privacy Rights (CalOPPA)">
            <p>California residents have the right to:</p>
            <ul className="mt-3 space-y-1 list-disc list-inside">
              <li>Know what personal information is collected and how it is used</li>
              <li>Request deletion of their personal information</li>
              <li>Equal service — we will not discriminate against you for exercising privacy rights</li>
            </ul>
            <p className="mt-3">We do not sell the personal information of our users.</p>
          </Section>

          <Section title="Third-Party Services">
            <p>Mira integrates the following third-party services:</p>
            <ul className="mt-3 space-y-1 list-disc list-inside">
              <li><strong>Supabase</strong> — authentication and user account management</li>
              <li><strong>Cloudinary</strong> — image storage and delivery</li>
              <li><strong>Qdrant</strong> — vector database for AI search</li>
              <li><strong>Railway</strong> — backend hosting</li>
              <li><strong>Vercel</strong> — frontend hosting</li>
            </ul>
            <p className="mt-3">Each of these services has its own privacy policy governing their data handling.</p>
          </Section>

          <Section title="Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time. We will notify you of
              significant changes through the Service. Continued use of Mira after changes
              are posted constitutes your acceptance of the updated policy.
            </p>
          </Section>

          <Section title="Contact Us">
            <p>
              If you have any questions about this Privacy Policy or want to exercise your
              data rights, please reach out through the support link in the app or open an
              issue on our GitHub repository.
            </p>
          </Section>

        </div>

        <div className="mt-16 pt-8 border-t border-primary/5">
          <Link
            href="/"
            className="text-sm font-bold font-label tracking-widest uppercase text-primary hover:opacity-70 transition-opacity"
          >
            ← Back to Mira
          </Link>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h2 className="font-headline text-lg font-bold text-primary">{title}</h2>
      {children}
    </div>
  );
}
